plugins {
  id 'parquito.common'
  id 'com.github.spotbugs'
  id 'com.diffplug.spotless'
}

spotless {
  java {
    googleJavaFormat('1.22.0')
  }
  groovyGradle {
    target('*.gradle')
    greclipse()
    trimTrailingWhitespace()
    leadingTabsToSpaces(2)
  }
  format "shellScripts", {
    target('*.sh')
    trimTrailingWhitespace()
    leadingTabsToSpaces(2)
  }
}

dependencies {
  compileOnly 'com.github.spotbugs:spotbugs-annotations:4.7.3'
}

spotbugs {
  excludeFilter = project.parent.file("spotbugs.excludes.xml")
}