plugins {
  id 'java'
}

jar {
  manifest {
    attributes (
        'Implementation-Title': "${project.group}.${project.name}",
        'Implementation-Version': "${version_string}",
        'Parquito-Group': "${project.group}",
        'Parquito-Artifact': "${project.name}",
        'Parquito-CommitSHA': "${commit_sha}",
    )
  }
}

java {
  targetCompatibility = javaVersion
  sourceCompatibility = javaVersion
}

tasks.withType(JavaCompile) {
  options.compilerArgs << '-Xlint:unchecked'
  options.deprecation = true
}

dependencies {
  testImplementation "org.junit.jupiter:junit-jupiter:5.14.2"
  testImplementation "org.junit.jupiter:junit-jupiter-api:5.14.2"
  testImplementation "org.junit.jupiter:junit-jupiter-params:5.14.2"
  testRuntimeOnly "org.junit.platform:junit-platform-launcher:1.13.4"
}

test {
  useJUnitPlatform()
  jvmArgs = [
      "-Xmx2g",
      "-XX:StartFlightRecording=jdk.ExecutionSample#period=1ms,dumponexit=true,filename=/tmp/parquito_tests_${System.currentTimeMillis()}.jfr",
      "-XX:+HeapDumpOnOutOfMemoryError",
      "-XX:HeapDumpPath=/tmp/parquito_tests_oom_${System.currentTimeMillis()}.hprof"
  ]
}